### ISSUE TITLE
Fix duplicate notifications

### ISSUE THREAD

**Issue by tanius** [edgeryders/dynalist_companion#44]
Please re-apply the changes I made in 9eae71b.

They have been overwritten in recent commit, but I think that's by mistake as it introduces an issue of sending lots of notifications to all kinds of users, not just those mentioned in the current task. Effectively, everyone is notified about the currently processed item who got mentioned or assigned in any item the script processed before the current one.

(@anuzement maybe you have an issue with your git development process that caused this change to be lost? git forces you to merge upstream ("online") changes before you can commit yours. You should do that carefully if there is a merge conflict, which means that the software can't mix the changes together and you have to do it manually.)

**Comment by anuzement** [comment]
> I think that's by mistake as it introduces an issue of sending lots of notifications to all kinds of users, not just those mentioned in the current task

It does not send others than mentioned in the tasks. It sends one email per tag to the respective user.

I don't think I have to explain to pro coders like you, but anyway let me explain to you and others as well. :)

`line = Explain to @user1 @user2.`
`mentions += re.findall('\s@([a-z.]+)', line)`

This script picks each individual @tag and stores in array for later use by email sender.
In this case mentions will be stored as array like `mentions = ['user1, 'user2']`
What happens if i remove **+**?

Well, its clear mentions array will be now `mentions = ['user2']`

Of course, same case for `#`

Why it was sending a lot of emails before?

I intentionally removed `readlines() ` . (I gotta think there was no effect of this, because worked well without this on my machine)

But I was horribly wrong, `for line in new_file if not in old file` was not reading  any line, thus `diff` variable was getting whole original content, and guess `diff` was parsed and did its job. :D

Do you think still I  should remove this `+`? :-)

**Comment by tanius** [comment]
> `line = Explain to @user1 @user2`
> `mentions += re.findall('\s@([a-z.]+)', line)`
> In this case mentions will be stored as array like `mentions = ['user1, 'user2']`
>
> What happens if i remove +?
> Well, its clear mentions array will be now mentions = ['user2']

Yes it helps when you explain your code, so I know how to explain back to you why it won't work :wink: 

And you will love a debugger. That's a very nice tool to have for learning programming, as you can see step by step what your code does, avoiding any guesswork. They can be a pain to set up though … but try it, and I'll help if needed.

Now about the `+`: the `+=` operator is just a shorthand form for "add to the current value". So this:

    mentions += re.findall('\s@([a-z.]+)', line)

is equivalent to this long form:

    mentions = mentions + re.findall('\s@([a-z.]+)', line)

With mentions initially set to `mentions = []` and the result of your regex being `['user1, 'user2']` as per the example, the results is:

   ⇒ mentions = [] + ['user1', 'user2'] = ['user1', 'user2']

No problem so far.

But the problem starts when the `for` loop runs the second time, to process the second line with notifications. Let's say `re.findall('\s@([a-z.]+)', line) = ['user3', 'user4'] for that line. `mentions` is still `['user1', 'user2']`, and now the new value is added:

    mentions += mentions + re.findall('\s@([a-z.]+)', line)
    ⇒ mentions = ['user1', 'user2'] + ['user3', 'user4'] = ['user1', 'user2', 'user3', 'user4']

You see? Now in addition to the correct audience of users 3-4, users 1-2 would also get an e-mail about this task. When you remove the `+` it does not mean (like you assume) that the assignment will only assign a single value from the array. It sets `mentions` to be the result of the function, so in your example:

    mentions = re.findall('\s@([a-z.]+)', line)`
    ⇒ mentions =  ['user1', 'user2']

That's what we want. And it will not aggregate values over multiple `for` loop runs, as it re-initializes `mentions` correctly each time, discarding its value from the previous `for` loop run.

**Comment by anuzement** [comment]
Admit that.
I was unaware of `for` loop activity. I used `re.match()` in previous version and after I used `re.findall()`,  I was unaware of of using it with `for` loop.
Thank you so much.
